### ISSUE TITLE
Header 的设定按钮

### ISSUE THREAD

**Issue by frankwei98** [Dasdaq/Dasdaq-web#30]
Header 的空白空间越来越少了

打算对右侧的功能按钮进行简化

具体
* 有一个 setting 按钮
* 点击按钮弹出 Modal 选单，允许用户设置语言、主题、默认 Crypto

**Comment by udspj** [comment]
～ing

**Comment by udspj** [comment]
done

**Comment by lychees** [comment]
LGTM, Good work.
