### ISSUE TITLE
钱包签名登录 Integration 

### ISSUE THREAD

**Issue by frankwei98** [Dasdaq/Dasdaq-web#33]
# 登录页

- [x] 显示 Metamask 登录、Scatter 登录

# 以太坊
- [x] 以太坊 Metamask 钱包验证绑定账户（需对接后端 API，详见 Slack 8.2 上午聊天）
- [x] 以太坊 Metamask 钱包验证登录 （ [Metamask 的博文](https://medium.com/metamask/scaling-web3-with-signtypeddata-91d6efc8b290) )
- [x] Detect MetaMask is installed or not, if not, disable the button
# EOS
- [x] EOS Scatter 钱包验证绑定账户（需对接后端 API，详见 Slack 8.2 上午聊天）
- [x] EOS Scatter 钱包验证签名登录 (in PR #37 by Frank，需要对接后端)

# 相关链接

[MetaMask 官方博客 Scaling Web3 with SignTypedData](https://medium.com/metamask/scaling-web3-with-signtypeddata-91d6efc8b290)

[Scatter 入门](https://get-scatter.com/docs/dev/getting-started)

**Comment by udspj** [comment]
eth ing

**Comment by frankwei98** [comment]
@udspj 
web3登录部分 没有对 web3 插件是否存在的检测，这个需要加上去
![image](https://user-images.githubusercontent.com/3261732/43678770-05568e9c-984c-11e8-9e7b-993a1c441dec.png)

**Comment by frankwei98** [comment]
Done in #48, i am closing this now.
