### ISSUE TITLE
用户中心优化

### ISSUE THREAD

**Issue by frankwei98** [Dasdaq/Dasdaq-web#47]
# 问题

用户访问用户中心，有 个人信息，修改密码，绑定第三方钱包，绑定第三方账户几个页面。

目前用户中心内的页面切换是基于 state 的 index 来操作，有以下问题：

* 用户一旦刷新页面，又得重新选择页面

* 一个组件类多个方法返回不同页面 JSX，不容易观察

# 解决方案

* 延伸用户中心页，分拆页面组件为单独的文件

* 用户中心子页面引入 React-Router，用户切换页面即操作路由

## Tasks

- [x] 分拆页面组件为单独的文件

- [x] 给 User 引入 React-Router，试图做子路由

**Comment by Deasoso** [comment]
finished。
